name: Scheduled HTTP Request

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  http-request:
    runs-on: ubuntu-latest
    steps:
    - name: Ping site
      env:
        NODE_SUBDOMAIN: ${{ secrets.NODE_SUBDOMAIN }}
      run: curl -X GET https://$NODE_SUBDOMAIN.onrender.com --verbose
