name: Scheduled HTTP Request

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  http-request:
    runs-on: ubuntu-latest
    steps:
    - name: Ping site
      env:
        NODE_SUBDOMAIN_1: ${{ secrets.NODE_SUBDOMAIN }}
        SITE_URL: https://${{ vars.NODE_SUBDOMAIN }}.onrender.com
      run: curl $SITE_URL --verbose
