name: Scheduled HTTP Request

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  http-request:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - name: Ping site
      env:
        SITE_URL: https://${{ secrets.NODE_SUBDOMAIN }}.onrender.com
      run: curl $SITE_URL --verbose
